/**
 * End-to-end smoke test for the data-package marketplace pivot.
 *
 *   1. Login as a seeded developer → submit a fresh package
 *   2. Wait for the evaluator to flip it from `evaluating` → `certified|rejected`
 *   3. Login as a seeded buyer → purchase the package
 *   4. Verify a `package_purchases` row exists and the ledger has paired entries
 *
 * Run:  pnpm exec ts-node --transpile-only scripts/smoke-test-package-marketplace.ts
 * Pre:  Demo seed has run (`pnpm run demo:seed`) and API is on :3000.
 *
 * Exits non-zero on any failure so CI can wire it up later.
 */

const API_BASE = process.env.SMOKE_API_BASE ?? 'http://localhost:3000';
const DEV_EMAIL = 'developer.fitness@dataclaus.demo';
const BUYER_EMAIL = 'buyer.brandone@dataclaus.demo';
const PASSWORD = 'demo1234';

interface LoginResp {
  data: { accessToken: string; user: { id: string; role: string } };
}

async function login(email: string): Promise<{ token: string; userId: string; role: string }> {
  const res = await fetch(`${API_BASE}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password: PASSWORD }),
  });
  if (!res.ok) {
    throw new Error(`Login failed for ${email}: ${res.status}`);
  }
  const json = (await res.json()) as LoginResp;
  return {
    token: json.data.accessToken,
    userId: json.data.user.id,
    role: json.data.user.role,
  };
}

async function authFetch(token: string, path: string, init?: RequestInit) {
  const res = await fetch(`${API_BASE}${path}`, {
    ...init,
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
      ...(init?.headers ?? {}),
    },
  });
  const body = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(
      `[${res.status}] ${path}: ${JSON.stringify(body).slice(0, 300)}`,
    );
  }
  return body;
}

function assert(cond: unknown, msg: string): asserts cond {
  if (!cond) throw new Error(`ASSERTION FAILED: ${msg}`);
}

async function main() {
  const startedAt = Date.now();
  console.log('🧪 Marketplace smoke test starting…');

  // 1. Login as developer
  const dev = await login(DEV_EMAIL);
  console.log(`  ✓ Logged in as developer (id=${dev.userId.slice(0, 8)})`);

  // 2. Submit package
  const createInput = {
    title: `Smoke Fitness Pack ${Date.now()}`,
    category: 'fitness',
    description: 'Generated by smoke-test-package-marketplace',
    claimed_metrics: {
      row_count: 10000,
      unique_users: 1500,
      date_range_start: '2025-10-01',
      date_range_end: '2025-12-31',
    },
    schema_json: {
      user_id: 'string',
      session_seconds: 'number',
      activity_type: 'string',
      recorded_at: 'timestamp',
    },
    sample_rows: [
      { user_id: 'u_s1', session_seconds: 320, activity_type: 'run', recorded_at: '2025-10-04T07:00:00Z' },
      { user_id: 'u_s2', session_seconds: 188, activity_type: 'cycle', recorded_at: '2025-10-04T08:00:00Z' },
      { user_id: 'u_s3', session_seconds: 905, activity_type: 'gym', recorded_at: '2025-10-04T19:00:00Z' },
      { user_id: 'u_s4', session_seconds: 421, activity_type: 'walk', recorded_at: '2025-10-05T06:55:00Z' },
      { user_id: 'u_s5', session_seconds: 250, activity_type: 'run', recorded_at: '2025-10-05T18:00:00Z' },
    ],
    price: 25.0,
  };
  const create = (await authFetch(dev.token, '/v1/packages', {
    method: 'POST',
    body: JSON.stringify(createInput),
  })) as { data: { id: string; status: string } };
  const packageId = create.data.id;
  console.log(`  ✓ Package submitted (id=${packageId.slice(0, 8)}, status=${create.data.status})`);

  // 2b. Regression guard — fetch the just-created package and assert that
  //     `sampleRows` round-trips as real objects, not `[[], [], ...]`. The
  //     DTO must carry `@Type(() => Object)` on sample_rows or class-transformer
  //     (with enableImplicitConversion in main.ts) silently corrupts each row.
  const readback = (await authFetch(dev.token, `/v1/packages/${packageId}`)) as {
    data: { sampleRows: unknown[] };
  };
  assert(
    Array.isArray(readback.data.sampleRows) && readback.data.sampleRows.length === createInput.sample_rows.length,
    `sampleRows length mismatch: sent ${createInput.sample_rows.length}, got ${readback.data.sampleRows?.length}`,
  );
  for (let i = 0; i < readback.data.sampleRows.length; i++) {
    const row = readback.data.sampleRows[i];
    assert(
      row !== null && typeof row === 'object' && !Array.isArray(row),
      `sampleRows[${i}] is not a plain object (got ${JSON.stringify(row)}); did the DTO drop @Type(() => Object)?`,
    );
    assert(
      Object.keys(row as Record<string, unknown>).length > 0,
      `sampleRows[${i}] has no keys — the row was corrupted to {} or []`,
    );
  }
  console.log(`  ✓ sampleRows round-trips intact (${readback.data.sampleRows.length} non-empty objects)`);

  // 3. Wait for evaluator
  let finalStatus = 'evaluating';
  let trustScore: number | null = null;
  for (let i = 0; i < 20; i++) {
    await new Promise((r) => setTimeout(r, 500));
    const res = (await authFetch(dev.token, `/v1/packages/${packageId}`)) as {
      data: { status: string; dataclausScore: number | null };
    };
    finalStatus = res.data.status;
    trustScore = res.data.dataclausScore;
    if (finalStatus !== 'evaluating' && finalStatus !== 'pending') break;
  }
  assert(
    finalStatus === 'certified' || finalStatus === 'rejected',
    `Evaluator stuck at ${finalStatus}`,
  );
  console.log(`  ✓ Evaluation complete: ${finalStatus} (score=${trustScore})`);

  // 4. Only certified packages can be purchased. If the deterministic stub
  //    rejected (low score is possible without ANTHROPIC_API_KEY), bail clean.
  if (finalStatus !== 'certified') {
    console.log(
      '  ⚠ Package not certified — smoke test cannot exercise purchase path. PASS (eval ran).',
    );
    console.log(`✨ Smoke test partial-pass in ${Date.now() - startedAt}ms`);
    return;
  }

  // 5. Login as buyer
  const buyer = await login(BUYER_EMAIL);
  console.log(`  ✓ Logged in as buyer (id=${buyer.userId.slice(0, 8)})`);

  // 6. Purchase
  const purchase = (await authFetch(buyer.token, `/v1/packages/${packageId}/purchase`, {
    method: 'POST',
    body: JSON.stringify({}),
  })) as {
    data: { purchase_id: string; download_token: string; ledger_transaction_id: string };
  };
  assert(purchase.data.purchase_id, 'purchase_id missing');
  assert(purchase.data.download_token, 'download_token missing');
  assert(purchase.data.ledger_transaction_id, 'ledger_transaction_id missing');
  console.log(`  ✓ Purchase complete (purchase=${purchase.data.purchase_id.slice(0, 8)})`);

  // 7. Verify my-purchases includes the row
  const mine = (await authFetch(buyer.token, '/v1/packages/purchases')) as {
    data: Array<{ packageId: string; amount: number }>;
  };
  const found = mine.data.find((p) => p.packageId === packageId);
  assert(found, 'purchase row not in /v1/packages/purchases');
  assert(Number(found.amount) === 25, `amount mismatch: ${found.amount}`);
  console.log('  ✓ Purchase visible in /v1/packages/purchases');

  // 8. Verify download works AND that downloaded rows are real objects, not [].
  //    Same regression guard as step 2b — the download endpoint is what the buyer
  //    actually consumes, so the contract must hold here too.
  const dl = (await authFetch(
    buyer.token,
    `/v1/packages/${packageId}/download?token=${encodeURIComponent(purchase.data.download_token)}`,
  )) as { data: { package: { sample_rows: unknown[] } } };
  assert(
    Array.isArray(dl.data.package.sample_rows) && dl.data.package.sample_rows.length >= 5,
    'sample_rows missing on download',
  );
  for (let i = 0; i < dl.data.package.sample_rows.length; i++) {
    const row = dl.data.package.sample_rows[i];
    assert(
      row !== null && typeof row === 'object' && !Array.isArray(row) && Object.keys(row as Record<string, unknown>).length > 0,
      `download sample_rows[${i}] is not a non-empty object: ${JSON.stringify(row)}`,
    );
  }
  console.log(`  ✓ Download returns ${dl.data.package.sample_rows.length} intact sample rows`);

  console.log(`✨ Smoke test PASS in ${Date.now() - startedAt}ms`);
}

main().catch((err) => {
  console.error('❌ Smoke test FAILED:', err.message ?? err);
  process.exit(1);
});
