name: DataClaus - CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          #for nx affected
          fetch-depth: 0

      # 1. NX Setup & Cache
      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g pnpm
      - uses: actions/cache@v3 # pnpm cache'i
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --frozen-lockfile
      - name: Determine Affected Projects
        uses: nrwl/nx-set-shas@v4 # finds the affected parts

      # 2. Go Setup
      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true # Go mod cache

      # downloads the necessary packages
      - name: Go Mod Download (apps/dataclaus-api)
        run: go mod download
        working-directory: apps/dataclaus-api

      # a. Format Kontrolü (Kalite Kuralı: go fmt bozuksa fail et)
      - name: Check Code Formatting (go fmt)
        run: |
          diff -u <(echo -n) <(gofmt -d .)

      # b. Statik Analiz (go vet)
      - name: Run Static Analysis (go vet)
        run: npx nx affected --target=lint --parallel=1

      # 4. BİRİM TESTLERİ (Hata Payı Yok)
      - name: Run Unit Tests (nx test)
        run: npx nx affected --target=test --parallel=1

      - name: Build All Affected Apps
        run: npx nx affected --target=build --parallel=2
